-- Per-user personalized lesson content, generated by Claude from the user's
-- assessment context and cached here (one row per user per lesson).
-- context_hash fingerprints the assessment answers used at generation time,
-- so retaking the assessment invalidates the cache naturally.

CREATE TABLE IF NOT EXISTS personalized_lessons (
  id           UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id      UUID        NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  lesson_id    TEXT        NOT NULL,
  track_id     TEXT        NOT NULL,
  content      TEXT        NOT NULL,
  context_hash TEXT        NOT NULL,
  model        TEXT,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (user_id, lesson_id)
);

ALTER TABLE personalized_lessons ENABLE ROW LEVEL SECURITY;

-- Reads scoped to the owner; all writes go through the service role in
-- /api/personalize, so no insert/update policies for regular users.
CREATE POLICY "personalized_lessons_select" ON personalized_lessons
  FOR SELECT USING (auth.uid() = user_id);
